# Generated by Django 2.2.7 on 2020-01-20 21:13

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_professor_midd_webid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='again',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='another',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='components',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Lectures'), ('B', 'Discussions'), ('C', 'Papers'), ('D', 'Readings'), ('E', 'Lab/Field work'), ('K', 'Problem sets'), ('F', 'Presentations'), ('G', 'Group work'), ('H', 'Screenings'), ('I', 'Final'), ('J', 'Tests/Midterms')], max_length=21),
        ),
        migrations.AlterField(
            model_name='review',
            name='grasp',
            field=models.CharField(choices=[('L', 'Lower'), ('A', 'Accurate'), ('H', 'Higher')], max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='prof_feedback',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='prof_help',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='prof_leading',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='prof_lecturing',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('P', 'The professor'), ('S', 'The students'), ('C', 'The coursework'), ('W', 'Work outside class'), ('N', 'Not valuable')], max_length=9),
        ),
        migrations.AlterField(
            model_name='review',
            name='why_flag',
            field=models.CharField(blank=True, choices=[('A', 'This comment contains hateful or obscene language.'), ('B', "This comment is not about this page's course or professor."), ('C', 'This comment is spam.')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='why_take',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'My major'), ('I', 'My minor'), ('D', 'Distribution requirement'), ('T', 'To try something new'), ('R', 'Recommendation from a friend')], max_length=9),
        ),
    ]
